name: Electron App Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    # リリースの作成とファイルのアップロード
    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: yarn install
        run: yarn install
      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest'}}
        run: |
          yarn build:win
      - name: Import Apple installer signing certificate
        if: ${{ matrix.os == 'macos-latest'}}
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_ID_APP }}
          p12-password: ${{ secrets.APPLE_DEV_ID_APP_PASS }}
      - name: Build macOS
        if: ${{ matrix.os == 'macos-latest'}}
        run: |
          mkdir -p ~/private_keys
          echo "${{ secrets.APPLE_API_KEY_BASE64 }}" > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

          xattr -cr .
          yarn build:mac
        env:
          # API Key 方式の環境変数
          APPLE_API_KEY: ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          sudo snap install snapcraft --classic
          yarn build:linux
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.zip
            dist/*.dmg
            dist/*.exe
            dist/*.snap
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
